#!/usr/bin/env sh

echo "Running cargo check..."
cargo check || exit 1

echo "Running formatter..."
cargo fmt -- --check || exit 1

echo "Running clippy..."
# cargo clippy || exit 1
cargo clippy --all-targets --all-features -- -D warnings || exit 1

echo "Checking markdown formatting..."
bunx prettier --check "**/*.md" || exit 1

echo "All checks passed - commit approved!"